### ISSUE TITLE
Wily fails when enabled on GitHub workflow

### ISSUE THREAD

**Issue by edmondo1984** [tonybaloney/wily#141]
**Describe the bug**
I have added a specific job to my Github Workflow without installing wily locally and Wily fails with a git error:

```
Failed to setup archiver: '<class 'git.exc.GitCommandError'> - Cmd('git') failed due to: exit code(128)
  cmdline: git diff --numstat 4b2122317b4775a75d30403fc158ea89bac3d204 ce16aee57f19e7e948a4794779d5aa5135b64e8f --
  stderr: 'fatal: bad object 4b2122317b4775a75d30403fc158ea89bac3d204''

```
**To Reproduce**
Add a job to a Github pipeline to your code like so:

```yml
  evaluate-complexity:
    name: Evaluate code complexity
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Install Wily and compile cache
      run: |
            pip install wily
            wily build my_proj
    - name: Compute code complexity diff with main
      run: "wily diff my_proj/ -r main"
      id: run_wily
```

**Expected behavior**
Build would succeed

**Additional context**
It's interesting that the git diff command copy-pasted on my machine works correctly
