### ISSUE TITLE
GitHub Actions workflow: git ls-tree error on wily diff command

### ISSUE THREAD

**Issue by mbell-volpe** [tonybaloney/wily#178]
Seeking guidance for git command error on _wily diff src/ -r HEAD^1 command that seems like some of the references may not be correct for the git tree object being passed as an argument:
![git-cmd-error-ls-tree](https://github.com/tonybaloney/wily/assets/134711893/2945922c-570f-48dd-88ea-8457714e1740)

**Comment by tonybaloney** [comment]
The checkout action in the workflow needs extra parameters. By default GitHub will do a shallow clone (ie not check out the history).

See https://wily.readthedocs.io/en/latest/ci.html#github-workflows

So your checkout action needs to look like this:

```yaml
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
```
