### ISSUE TITLE
build time

### ISSUE THREAD

**Issue by bohdansolovey** [tonybaloney/wily#76]
hi, could you advise how to speed up the build command? I tried to run it inside of pipeline, and it takes ~15 min. And is there any way to pass a lot of arguments to the report command as implemented for diff? because my diff command doesnt work

**Comment by tonybaloney** [comment]
if you're running inside a pipeline, then I would only index 1 revision, by default it will index 50 revisions, and if you only care about the last commit, then this is a waste of resources.

`wily build -n 1 <dest>`

I'm not sure what you mean about the arguments, please could you provide an example of what you're trying to do?

**Comment by bohdansolovey** [comment]
> if you're running inside a pipeline, then I would only index 1 revision, by default it will index 50 revisions, and if you only care about the last commit, then this is a waste of resources.
> 
> `wily build -n 1 <dest>`
> 
> I'm not sure what you mean about the arguments, please could you provide an example of what you're trying to do?

hello, i try to get some metrics in the gitlab ci pipeline, so i clone my repo in some directory in docker image( i can get history of commits)
`
```yaml
test wily:
  image: python:3.7
  stage: test
  before_script:
    - git checkout backend/dev_test_metrics
    - pip install wily
    - python -m wily build -n 10
  script:
    - find ./backend/api -name "*s.py" ! -name "*test*" | xargs python -m wily diff  --changes-only --no-detail
    - python -m wily report -n 1 backend/api/v1 # now better than diff
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run  --rm $CONTAINER_TEST_IMAGE /bin/bash -c "; find ./backend/api -name "*s.py" ! -name "*test*" | xargs python -m wily diff  --changes-only --no-detail "

````
and i want to pass arguments in standart way, not like in exampe( i dont need metrics for my tests  etc). 
**IN general,** i need to see changes in code like with pre-commit, but when i use gitlab ci, and i try to implement this
